### ISSUE TITLE
gitlab integration

### ISSUE THREAD

**Issue by Kuznetsov-Ilia** [containerum/chkit#84]
Hello, my sweet lovely kittens!
I'm trying to use your awesome service in pair with gitlab CI/CD.
Pls, tell me, what is your vision of piping this way.
As I know, you don't have private registry for docker containers, so there must be the way to use private images from dockerhub/gitlab. How to setup this authorization process?

**Comment by Kuznetsov-Ilia** [comment]
Probably you should implement create secret and add option to pod configuration to use this secret  https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#log-in-to-docker

**Comment by Kuznetsov-Ilia** [comment]
hm, you have configMaps that can be a workaround, but https://stackoverflow.com/questions/36912372/kubernetes-secrets-vs-configmaps

**Comment by kfeofantov** [comment]
Hi!

1) chkit has method Set Image, it allows you to change the version of the image. For convenience, we packed the chkit in Docker ( https://hub.docker.com/r/containerum/chkit ). This should simplify the work with the platform in CI Pipeline.

For Gitlab Pipeline it may look like:
```
deploy:
  image: containerum/chkit:latest
  script:
    - chkit login -u ${USER} -p ${PASS} -n ${NS}
    - chkit set image -d ${DEPLOY_NAME} -i ${NEW_IMAGE} -f 
```
    
2) We added secrets for third-party and private registry and soon they will be available.

Currently, both functions are tested. Set Image function will be available next week.
